const CARDS = [
    '1~red',
    '2~red',
    '3~red',
    '4~red',
    '5~red',
    '1~green',
    '2~green',
    '3~green',
    '4~green',
    '5~green',
    '1~aquamarine',
    '2~aquamarine',
    '3~aquamarine',
    '4~aquamarine',
    '5~aquamarine',
    '1~orange',
    '2~orange',
    '3~orange',
    '4~orange',
    '5~orange',
    '1~gray',
    '2~gray',
    '3~gray',
    '4~gray',
    '5~gray',
    '<i class="fa-sharp fa-solid fa-ban"></i>~red',
    '<i class="fa-sharp fa-solid fa-ban"></i>~green',
    '<i class="fa-sharp fa-solid fa-ban"></i>~aquamarine',
    '<i class="fa-sharp fa-solid fa-ban"></i>~orange',
    '<i class="fa-sharp fa-solid fa-ban"></i>~gray',
]

